FROM balenalib/%%BALENA_MACHINE_NAME%%-node:14.16-stretch-build as build

COPY ./package.json ./package-lock.json ./
RUN npm i --only=production

COPY ./src ./src
RUN npm run build:controller


# The run time container that will go to devices
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:14.16-stretch-run

# Grab our node modules for the build step
COPY --from=build ./node_modules ./node_modules
COPY --from=build ./dist ./

ENV UDEV=1

CMD ["node", "controller/index.js"]
